# Generated by Django 5.2.7 on 2025-11-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('nota', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='barbearias/')),
            ],
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='barbearia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbeiros', to='system_app.barbearia'),
        ),
    ]
